builds:
  - main: ./cmd/kubeletmein
    binary: kubeletmein
    env:
    - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
archive:
  format: binary
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
